language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

branches:
  only:
    - /^master$/

before_install:
  - composer install

matrix:
  allow_failures:
      - php: 7.2

env:
    TRELLIS_CONFIG_DIR=test/resources/config/

script:
  - composer test

