language: php
php:
    - 5.6
    - 7.0
    - 7.1

branches:
  only:
    - /^master$/

before_install:
  - composer install

env:
    TRELLIS_CONFIG_DIR=test/resources/config/

script:
  - composer test

