language: php
php:
    - 7.1
    - 7.2
    - 7.3

branches:
  only:
    - /^main$/

before_install:
  - composer install

env:
    TRELLIS_CONFIG_DIR=tests/resources/config/

script:
  - composer test

