version: '{build}'
skip_tags: true
build: false
clone_folder: C:\projects\static-ldp

init:
    - SET PATH=C:\Program Files\OpenSSL;C:\tools\php71;%PATH%
    - SET COMPOSER_NO_INTERACTION=1

install:
    - ps: Set-Service wuauserv -StartupType Manual
    - cinst -y OpenSSL.Light
    - cinst -y php --version 7.1.13
    - cd c:\tools\php71
    - copy php.ini-production php.ini
    - echo date.timezone="UTC" >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - cd c:\projects\static-ldp
    - php -r "readfile('http://getcomposer.org/installer');" | php
    - php composer.phar install --prefer-source --no-interaction

build_script:
    - cd c:\projects\static-ldp
    - php composer.phar install

test_script:
    - cd c:\projects\static-ldp
    - php composer.phar test
