version: '{build}'
skip_tags: true

install:
    - cinst -y php
    - SET PATH=C:\tools\php71;%PATH%
    - php -r "readfile('http://getcomposer.org/installer');" | php
    - php composer.phar install --prefer-source --no-interaction

build_script:
    - php composer.phar install

test_script:
    - php composer.phar test

matrix:
    fast_finish: true
