main:
  path: /{path}
  defaults:
    path: ''
  requirements:
    path: '.+'
  methods: HEAD|GET
  controller: App\Controller\ResourceController::getResource

options:
  path: /
  methods: OPTIONS
  controller: App\Controller\ResourceController::options
